---
title: "Plot creation"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
#load packages
require(learnr)
require(knitr)
require(png)
require(grid)

#options
knitr::opts_chunk$set(echo = FALSE)

#load data used in exercises

```

## Introduction 

- ggplot buid in layers, figure ggplot_layers.png in Images folder
- Cheat sheets

### Grammar of ggplot

- Maybe include ggplot_grammar.png from Linda

## Simple plot

- data 
- aes

### Geom layers

- geom layers
- overlaying lines and points

### Exercise

- Simple plotting exercise with geom_line and geom_point

## Complex plot

- group variable
- colour variable
- facetting

### Quiz

- Questions about what to set in the aes and what not

### Exercise

- Replace ? in the code to recreate the given plot (aes(group = ?, colour = ?) etc. See ggplot_group_exercise.png for example I based this exercise on.
- Add facet_ to create individual plots


## Beautiful plot

•	set labels 
•	aes colour discrete vs continuous
•	Colour palates
•	scale the aesthetics
•	Themes (set theme_bw), call predefined theme before theme options

### Exercise

- Change colour of id to discrete Hint: check data type, change data type, set colour in aes. See ggplot_colour_exercise.png for the example I based this exercise on. 
- Recreate example plot? 

## Multiple plots

- Par
- Patchwork very interesting and useful package https://patchwork.data-imaginist.com/

## Everything combined

- Large exercise of creating a complicated plot with multiple layers
- R course 2017 : Hands on exercise 7 -> adapted
